### ISSUE TITLE
駅の方角とそこまでの距離を出す機能をつける

### ISSUE THREAD

**Issue by 0x307e** [exp-tk/NearStation#30]
駅の方角がわからなくなった人に対して迷わず到達できるような仕組みを入れる。

https://twitter.com/tinykitten8/status/1466770528233213956

このアプリみたいな感じで実装すると迷わなくて良さそう。
https://apps.apple.com/jp/app/waaaaay-%E3%81%86%E3%81%87%E3%83%BC%E3%81%84/id792381884

**Comment by TinyKitten** [comment]
多分動かんと思うけど作ってて飽きたので公開した
https://github.com/TinyKitten/NearStation/pull/31
